// Copyright 2026 Grug Huhler
//
// License: BSD-2-Clause (SPDX)
//
// This file was generated by AI from a chat window and then reviewed
// and editted as needed.
//
// results intended to be viewed using Gowin Analysis Oscilloscope

`include "global_defs.v"

module top (
   input  logic sysclk,
   input  logic btn1,
   output logic led0,
   output logic led1
);

   logic [31:0] data_a [7:0] = '{
      7: 32'h3f800000, // 1.0f
      6: 32'h40000000, // 2.0f
      5: 32'h40400000, // 3.0f
      4: 32'h40800000, // 4.0f
      3: 32'h40a00000, // 5.0f
      2: 32'h40c00000, // 6.0f
      1: 32'h40e00000, // 7.0f
      0: 32'h41000000  // 8.0f
   };

   logic [31:0] data_b [7:0] = '{
      7: 32'h40000000,
      6: 32'h40400000,
      5: 32'h40800000, 
      4: 32'h40a00000,
      3: 32'h40c00000,
      2: 32'h40e00000,
      1: 32'h41000000,
      0: 32'h41100000
   };

   logic [31:0] correct [7:0] = '{
      7: 32'h40000000, // 2.0f * 1.0f = 32'h40000000
      6: 32'h40c00000, // 3.0f * 2.0f = 32'h40c00000
      5: 32'h41400000, // 4.0f * 3.0f = 32'h41400000
      4: 32'h41a00000, // 5.0f * 4.0f = 32'h41a00000
      3: 32'h41f00000, // 6.0f * 5.0f = 32'h41f00000
      2: 32'h42280000, // 7.0f * 6.0f = 32'h42280000
      1: 32'h42600000, // 8.0f * 7.0f = 32'h42600000
      0: 32'h42900000  // 9.0f * 8.0f = 32'h42900000
   };

   logic [31:0] result;
   logic [2:0]  cnt = 3'b0;
   logic [7:0]  err_cnt = 8'b0;
   logic        rst_n;

// Unpressed button state differs between board types
`ifdef BOARD_9K
   assign rst_n = btn1;
`endif
`ifdef BOARD_20K
   assign rst_n = ~btn1;
`endif

   logic [31:0] correct2;

   assign correct2 = correct[cnt]; // Allows GAO to see correct

   assign led0 = ~(err_cnt > 8'd8); // First 3 wrong due to latency
   assign led1 =  |result;  // Prevents everything from being swept.

   Gowin_rPLL your_instance_name(
      .clkout(clk), // Slow down for GAO
      .clkin(sysclk)
   );

   FP_Mult_Top ip_mult (
      .clk    (clk),
      .rstn   (rst_n),
      .data_a (data_a[cnt]),
      .data_b (data_b[cnt]),
      .result (result)
    );

   always @(posedge clk or negedge rst_n)
     if (rst_n == 1'b0) begin
        cnt <= 3'b0;
        err_cnt <= 8'b0;
     end else begin
        cnt <= cnt + 1'b1;
        if (result != correct[cnt - 3'd3]) // -3 due to latency
           err_cnt <= (err_cnt < 8'd255) ? err_cnt + 1'b1 : 8'd255;
     end

endmodule
