/*
 * Copyright 2026 Grug Huhler
 *
 * License: BSD-2-Clause (SPDX)
 *
 * This file was generated by AI from a chat window and then reviewed and
 * editted as needed.
 *
 * fp.c - Raspberry Pi Zero SPI Controller for FPGA Floating Point Test
 *
 * Hardware Wiring Guide (Raspberry Pi Zero):
 * - MOSI: SPI0_MOSI -> GPIO 10 (Physical Pin 19)
 * - MISO: SPI0_MISO -> GPIO 9  (Physical Pin 21)
 * - SCLK: SPI0_SCLK -> GPIO 11 (Physical Pin 23)
 * - CS:   SPI0_CE0  -> GPIO 8  (Physical Pin 24)
 * - GND:  Ground    -> (e.g., Physical Pin 20 or 25)
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <linux/spi/spidev.h>

#define SPI_DEVICE "/dev/spidev0.0"
#define SPI_SPEED  1000000 // 1 MHz

int spi_fd = -1;

void spi_init()
{
  spi_fd = open(SPI_DEVICE, O_RDWR);
  if (spi_fd < 0) {
    perror("Warning: Failed to open SPI device");
    printf("Running in disconnected mode. SPI commands will be ignored, but parser will still run.\n");
    return;
  }
    
  uint8_t mode = SPI_MODE_0;
  if (ioctl(spi_fd, SPI_IOC_WR_MODE, &mode) < 0) {
    perror("Failed to set SPI mode");
    exit(1);
  }
    
  uint8_t bits = 8;
  if (ioctl(spi_fd, SPI_IOC_WR_BITS_PER_WORD, &bits) < 0) {
    perror("Failed to set SPI bits");
    exit(1);
  }
    
  uint32_t speed = SPI_SPEED;
  if (ioctl(spi_fd, SPI_IOC_WR_MAX_SPEED_HZ, &speed) < 0) {
    perror("Failed to set SPI speed");
    exit(1);
  }
}

void spi_transfer(uint8_t *tx, uint8_t *rx, int len)
{
  if (spi_fd < 0) return; // Disconnected mode
    
  struct spi_ioc_transfer tr = {
    .tx_buf = (unsigned long)tx,
    .rx_buf = (unsigned long)rx,
    .len = len,
    .delay_usecs = 0,
    .speed_hz = SPI_SPEED,
    .bits_per_word = 8,
  };
    
  if (ioctl(spi_fd, SPI_IOC_MESSAGE(1), &tr) < 1) {
    perror("Warning: Failed to send SPI message");
  }
}

void write_reg(uint8_t addr, uint32_t data)
{
  uint8_t tx[5];
  uint8_t rx[5];
    
  // Command byte: Bit 7 = 1 (Write), Bits 6:0 = addr
  tx[0] = 0x80 | (addr & 0x7F);
    
  // Little endian data
  tx[1] = (data >> 0) & 0xFF;
  tx[2] = (data >> 8) & 0xFF;
  tx[3] = (data >> 16) & 0xFF;
  tx[4] = (data >> 24) & 0xFF;

  spi_transfer(tx, rx, 5);
}

uint32_t read_reg(uint8_t addr)
{
  uint8_t tx[5];
  uint8_t rx[5];
  memset(tx, 0, sizeof(tx));
  memset(rx, 0, sizeof(rx));
    
  // Command byte: Bit 7 = 0 (Read), Bits 6:0 = addr
  tx[0] = addr & 0x7F;

  spi_transfer(tx, rx, 5);
    
  // Combine rx[1] to rx[4] as little-endian
  uint32_t data = ((uint32_t)rx[1] << 0) |
    ((uint32_t)rx[2] << 8) |
    ((uint32_t)rx[3] << 16) |
    ((uint32_t)rx[4] << 24);

  return data;
}

int wait_ready(int timeout_ms)
{
  int elapsed = 0;

  while (elapsed < timeout_ms) {
    uint32_t ctrl = read_reg(0);
    if (ctrl & (1 << 30)) { // bit 30 is ready
      return 1;
    }
    usleep(1000);
    elapsed++;
  }

  return 0; // timeout
}

uint32_t float_to_u32(float f)
{
  union { float f; uint32_t u; } v;
  v.f = f;

  return v.u;
}

float u32_to_float(uint32_t u)
{
  union { uint32_t u; float f; } v;
  v.u = u;

  return v.f;
}


int main()
{
  spi_init();
    
  char line[256];
  printf("fp> ");

  while (fgets(line, sizeof(line), stdin)) {
    char cmd[32];
    float arg1 = 0.0f, arg2 = 0.0f;
    int parsed = sscanf(line, "%31s %f %f", cmd, &arg1, &arg2);
        
    if (parsed >= 1) {
      int op = 0;
      int is_comp = 0;
            
      if (strcmp(cmd, "add") == 0 && parsed == 3) op = 1;
      else if (strcmp(cmd, "sub") == 0 && parsed == 3) op = 2;
      else if (strcmp(cmd, "mult") == 0 && parsed == 3) op = 3;
      else if (strcmp(cmd, "div") == 0 && parsed == 3) {
        if (arg2 == 0.0f) {
          printf("Error: Division by zero is not allowed.\n");
          goto next;
        }
        op = 4;
      } else if (strcmp(cmd, "sqrt") == 0 && parsed >= 2) {
        if (arg1 < 0.0f) {
          printf("Error: Square root of a negative number is not allowed.\n");
          goto next;
        }
        op = 5;
      } else if (strcmp(cmd, "ln") == 0 && parsed >= 2) {
        if (arg1 <= 0.0f) {
          printf("Error: ln argument must be positive\n");
          goto next;
        }
        op = 7;
      } else if (strcmp(cmd, "comp") == 0 && parsed == 3) {
        op = 6;
        is_comp = 1;
      } else if (strcmp(cmd, "reset") == 0) {
        write_reg(0, 0x80000000); // Reset FPGA without starting operation
        printf("FPGA reset signal sent.\n");
        goto next;
      } else if (strcmp(cmd, "exit") == 0 || strcmp(cmd, "quit") == 0) {
        break;
      } else {
        printf("Invalid command or arguments. Commands: add, sub, mult, div, sqrt,\n");
        printf("                                        ln, comp, reset, exit\n");
        goto next;
      }
            
      // Send arguments
      write_reg(1, float_to_u32(arg1));
      if ((op != 5) && (op !=7)) { // ln, sqrt only need arg1
        write_reg(2, float_to_u32(arg2));
      }
            
      // Start operation
      write_reg(0, op);
            
      // Wait for ready
      if (!wait_ready(1000)) {
        printf("Error: FPGA operation timed out (ready bit not set). Check FPGA connection/logic.\n");
      } else {
        uint32_t result_u32 = read_reg(3);
        
        if (is_comp) {
          if (result_u32 == 0) printf("equal\n");
          else if (result_u32 == 1) printf("greater than\n");
          else if (result_u32 == 2) printf("less than\n");
          else printf("Error: Unexpected comp result %u (invalid bits received)\n", result_u32);
        } else {
          float result_f = u32_to_float(result_u32);
          printf("Result: %f\n", result_f);
        }
      }
    }

  next:
    printf("fp> ");
  }
    
  if (spi_fd >= 0) close(spi_fd);

  return 0;
}
