// Copyright 2026 Grug Huhler
//
// License: BSD-2-Clause (SPDX)
//
// This file was generated by AI from a chat window and then reviewed and
// editted as needed.

module fp_math_core #(
    // There are other delays in additon to this...
    // This is not a high-performance implementation.
    parameter DELAY_CYCLES = 3
)(
    input  logic        sysclk,
    input  logic        rstn,
    
    input  logic        write_en,
    input  logic [6:0]  addr,
    input  logic [31:0] wdata,
    output logic [31:0] rdata
);

    logic [31:0] reg_arg1;
    logic [31:0] reg_arg2;
    logic [31:0] reg_result;

    logic        ready;
    logic [3:0]  current_op;

    always_comb begin
        case (addr)
            7'd0: rdata = {1'b0, ready, 26'd0, current_op};
            7'd1: rdata = reg_arg1;
            7'd2: rdata = reg_arg2;
            7'd3: rdata = reg_result;
            default: rdata = 32'd0;
        endcase
    end

    // Gowin IP Connections
    logic [31:0] add_sub_res, mult_res, div_res, sqrt_res, nat_log_res;
    logic aeb, agb;
    logic [31:0] comp_res;
    
    // Result encoding: 0 = Equal, 1 = Greater Than, 2 = Less Than
    assign comp_res = aeb ? 32'd0 : (agb ? 32'd1 : 32'd2);

    logic add_sub_op;

    FP_Add_Sub_Top ip_add_sub (
        .clk    (sysclk),
        .rstn   (rstn),
        .op     (add_sub_op),
        .data_a (reg_arg1),
        .data_b (reg_arg2),
        .result (add_sub_res)
    );

    FP_Mult_Top ip_mult (
        .clk    (sysclk),
        .rstn   (rstn),
        .data_a (reg_arg1),
        .data_b (reg_arg2),
        .result (mult_res)
    );

    FP_Div_Top ip_div (
        .clk    (sysclk),
        .rstn   (rstn),
        .data_a (reg_arg1),
        .data_b (reg_arg2),
        .result (div_res)
    );

    FP_Comp_Top ip_comp (
        .clk    (sysclk),
        .rstn   (rstn),
        .data_a (reg_arg1),
        .data_b (reg_arg2),
        .aeb    (aeb),
        .agb    (agb)
    );

    FP_Sqrt_Top ip_sqrt (
        .clk    (sysclk),
        .rstn   (rstn),
        .data_a (reg_arg1),
        .result (sqrt_res)
    );

   FP_Natural_Logarithm_Top ip_nat_log (
        .clk(sysclk),
        .rstn(rstn),
        .ce(1'b1),
        .data(reg_arg1),
        .result(nat_log_res),
        .nan(), // unused
        .zero() // unused
   );

    // Execution State Machine
    typedef enum logic [1:0] {IDLE, CALC, DONE} state_t;
    state_t state;
    
    logic [7:0] delay_cnt;

    always_ff @(posedge sysclk or negedge rstn) begin
        if (!rstn) begin
            state <= IDLE;
            ready <= 1'b1;
            reg_arg1 <= 32'd0;
            reg_arg2 <= 32'd0;
            reg_result <= 32'd0;
            delay_cnt <= 8'd0;
            current_op <= 4'd0;
            add_sub_op <= 1'b0;
        end else begin
            if (write_en) begin
                if (addr == 7'd0) begin
                    if (wdata[31]) begin
                        // Software Reset
                        state <= IDLE;
                        ready <= 1'b1;
                        current_op <= 4'd0;
                    end else if (wdata[3:0] != 4'd0 && ready) begin
                        // Trigger Calculation
                        current_op <= wdata[3:0];
                        ready <= 1'b0;
                        state <= CALC;
                        delay_cnt <= DELAY_CYCLES;
                        if (wdata[3:0] == 4'd1) add_sub_op <= 1'b0; // Add
                        else if (wdata[3:0] == 4'd2) add_sub_op <= 1'b1; // Sub
                    end
                end else if (addr == 7'd1) begin
                    reg_arg1 <= wdata;
                end else if (addr == 7'd2) begin
                    reg_arg2 <= wdata;
                end
            end

            case (state)
                IDLE: begin
                    // Wait
                end
                CALC: begin
                    if (delay_cnt == 0) begin
                        state <= DONE;
                    end else begin
                        delay_cnt <= delay_cnt - 1'b1;
                    end
                end
                DONE: begin
                    case (current_op)
                        4'd1: reg_result <= add_sub_res;
                        4'd2: reg_result <= add_sub_res;
                        4'd3: reg_result <= mult_res;
                        4'd4: reg_result <= div_res;
                        4'd5: reg_result <= sqrt_res;
                        4'd6: reg_result <= comp_res;
                        4'd7: reg_result <= nat_log_res;
                        default: reg_result <= 32'd0;
                    endcase
                    ready <= 1'b1;
                    current_op <= 4'd0;
                    state <= IDLE;
                end
            endcase
        end
    end

endmodule
