// Copyright 2026 Grug Huhler
//
// License: BSD-2-Clause (SPDX)
//
// This file was generated by AI from a chat window and then reviewed and
// editted as needed.

module fp_top (
    input  logic sysclk,
    input  logic btn1,
    
    input  logic SCLK,
    input  logic CS,
    input  logic MOSI,
    output logic MISO
);

    logic rstn;
    // btn1 is active high when pressed, we need active low internally
    assign rstn = ~btn1; 

    logic        write_en;
    logic [6:0]  addr;
    logic [31:0] wdata;
    logic [31:0] rdata;

    spi_target spi_target_inst (
        .sysclk   (sysclk),
        .rstn     (rstn),
        .sclk     (SCLK),
        .csn      (CS),
        .mosi     (MOSI),
        .miso     (MISO),
        .write_en (write_en),
        .addr     (addr),
        .wdata    (wdata),
        .rdata    (rdata)
    );

    fp_math_core #(
        .DELAY_CYCLES(4)
    ) fp_math_core_inst (
        .sysclk   (sysclk),
        .rstn     (rstn),
        .write_en (write_en),
        .addr     (addr),
        .wdata    (wdata),
        .rdata    (rdata)
    );

endmodule
