// Copyright 2026 Grug Huhler
//
// License: BSD-2-Clause (SPDX)
//
// This file was generated by AI from a chat window and then reviewed and
// editted as needed.

module spi_target (
    input  logic        sysclk,
    input  logic        rstn,
    
    input  logic        sclk,
    input  logic        csn,
    input  logic        mosi,
    output logic        miso,

    output logic        write_en,
    output logic [6:0]  addr,
    output logic [31:0] wdata,
    input  logic [31:0] rdata
);

    logic [2:0] sclk_sync, csn_sync, mosi_sync;
    always_ff @(posedge sysclk or negedge rstn) begin
        if (!rstn) begin
            sclk_sync <= 3'b000;
            csn_sync  <= 3'b111;
            mosi_sync <= 3'b000;
        end else begin
            sclk_sync <= {sclk_sync[1:0], sclk};
            csn_sync  <= {csn_sync[1:0],  csn};
            mosi_sync <= {mosi_sync[1:0], mosi};
        end
    end

    logic sclk_rise, sclk_fall, csn_active;
    assign sclk_rise  = (sclk_sync[2:1] == 2'b01);
    assign sclk_fall  = (sclk_sync[2:1] == 2'b10);
    assign csn_active = ~csn_sync[1];
    logic mosi_val;
    assign mosi_val   = mosi_sync[1];

    logic [5:0] bit_cnt;
    logic [7:0] shift_reg_in;
    logic [31:0] assembled_data;
    logic is_write;
    
    logic [31:0] miso_shift_reg;

    always_ff @(posedge sysclk or negedge rstn) begin
        if (!rstn) begin
            bit_cnt <= '0;
            shift_reg_in <= '0;
            assembled_data <= '0;
            write_en <= 1'b0;
            addr <= '0;
            wdata <= '0;
            is_write <= 1'b0;
            miso <= 1'b0;
            miso_shift_reg <= '0;
        end else begin
            write_en <= 1'b0; // Pulse

            if (!csn_active) begin
                bit_cnt <= '0;
                miso <= 1'b0;
            end else begin
                if (sclk_rise) begin
                    shift_reg_in <= {shift_reg_in[6:0], mosi_val};
                    
                    if (bit_cnt == 7) begin
                        is_write <= shift_reg_in[6];
                        addr <= {shift_reg_in[5:0], mosi_val};
                    end else if (bit_cnt == 15) begin
                        assembled_data[7:0] <= {shift_reg_in[6:0], mosi_val};
                    end else if (bit_cnt == 23) begin
                        assembled_data[15:8] <= {shift_reg_in[6:0], mosi_val};
                    end else if (bit_cnt == 31) begin
                        assembled_data[23:16] <= {shift_reg_in[6:0], mosi_val};
                    end else if (bit_cnt == 39) begin
                        if (is_write) begin
                            write_en <= 1'b1;
                            wdata <= { {shift_reg_in[6:0], mosi_val}, assembled_data[23:0] };
                        end
                    end
                    bit_cnt <= bit_cnt + 1'b1;
                end
                
                if (sclk_fall) begin
                    if (bit_cnt == 8 && !is_write) begin
                        // rdata is valid combinatorially from addr
                        // Byte 0 is transmitted first (Little Endian).
                        // MSB of Byte 0 is transmitted first.
                        miso <= rdata[7];
                        miso_shift_reg <= {rdata[6:0], rdata[15:8], rdata[23:16], rdata[31:24], 1'b0};
                    end else if (bit_cnt > 8 && bit_cnt <= 40 && !is_write) begin
                        miso <= miso_shift_reg[31];
                        miso_shift_reg <= {miso_shift_reg[30:0], 1'b0};
                    end
                end
            end
        end
    end
endmodule
